### ISSUE TITLE
Missing error handler on `socket`. when trying to export a preset

### ISSUE THREAD

**Issue by xavicampa** [schmic/ac-server-ctrl#1]
Missing error handler on `socket`.
TypeError: undefined is not a function
    at Socket.validatePreset (C:\Users\javi\Desktop\ac-monitor-master\libs\socke
t-handler-admin.js:15:26)
    at Socket.emit (events.js:110:17)
    at Socket.onevent (C:\Users\javi\Desktop\ac-monitor-master\node_modules\sock
et.io\lib\socket.js:330:8)
    at Socket.onpacket (C:\Users\javi\Desktop\ac-monitor-master\node_modules\soc
ket.io\lib\socket.js:290:12)
    at Client.ondecoded (C:\Users\javi\Desktop\ac-monitor-master\node_modules\so
cket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (C:\Users\javi\Desktop\ac-monitor-master\node_module
s\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.j
s:134:20)
    at Decoder.add (C:\Users\javi\Desktop\ac-monitor-master\node_modules\socket.
io\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (C:\Users\javi\Desktop\ac-monitor-master\node_modules\socke
t.io\lib\client.js:175:18)
    at Socket.emit (events.js:107:17)
    at Socket.onPacket (C:\Users\javi\Desktop\ac-monitor-master\node_modules\soc
ket.io\node_modules\engine.io\lib\socket.js:99:14)

**Comment by xavicampa** [comment]
Sorry, wrong project. This belongs to ac-monitor.
